from src.connection.client import _get_token

token = _get_token()
print(token)

token = "_B5bEEfOIbskMmiD6ADeVfRZZJFdxXJ1T_oGmDY1YTZrrBFEF2irFNbNQRo8jWUW2hM7GGOMROTa_jSO_xRFB_h-XfjIgTKBuQlWK1lJtHrN74R2hfxLVrwQv02tSIRKuSaGDt8q6urwyonLFKpFCGRiAvfcwGTnpjTNHeaPBOlVhDhk9lnyUXwy5SIUxYf4AIRiXTQXISKvp2BRP8yfPEDHqPyTWoWIIn30CWnfbaUN0ou8jxyykwkbp7sUSUJSriZX-f3sPjt0RuRev1c8i0TiO-DV6r9B9lBk-6qEWGWo"


# valudate = validate_token(token)
#
# print(valudate)
